### ISSUE TITLE
No need to work Hard

### ISSUE THREAD

**Issue by HostZero** [olegsvs/aicp_device_ark_benefit_m7#2]
Hereby In 2 days I will rise new trees, remove previous trees etc..

Here By I will rise a common tree like mediatek_mt6735-common

So Ark Benefit and My Device can use it as similar config.

:)

**Comment by olegsvs** [comment]
if I can find the time

**Comment by HostZero** [comment]
Hmmm, Where ad our trees are fully depending on MTK Hardware Tweaks which I don't like, I love to be with simple tree without any MTK Tweaks.

**Comment by olegsvs** [comment]
Alas , you buy mtk  :3

**Comment by HostZero** [comment]
?What does that mean? Anyways My tree will be based on mt6582 of sprout and modify to mt6735
